extreme-todo/frontend

.eslintrc.js, jest-puppeteer.config.js, jest.config.js, package-lock.json, package.json, src/test/components/Welcome.test.tsx, tsconfig.eslint.json, tsconfig.json, yarn.lock
린트 에러 수정된 거라도 PR해서 merge하겠습니다.
=> Feature/22 login e2e 테스트 작성하기

globalSetup.js, globalTeardown.js, jest-puppeteer.config.js, jest.config.js, package-lock.json, package.json, src/test/components/Welcome.test.tsx
page is not defined에 대한 에러는 여전하다
=> Update : globalSetup and globalTeardown 설정

public/icons/add.svg, public/icons/hamburger.svg, src/App.tsx, src/atoms/ProgressButtonAtom.tsx, src/atoms/index.ts, src/components/MainTodo.tsx, src/components/index.ts, src/molecules/Clock.tsx, src/molecules/SideButtons.tsx, src/molecules/index.ts, src/organisms/CurrentTodoCard.tsx, src/organisms/index.ts, src/test/molecules/Clock.test.tsx
두 번째 페이지의 전체적인 레이아웃을 잡았습니다.
molecules/Clock.tsx 를 제외하고는 테스트 코드 적용하지 않았습니다.
작업한 컴포넌트는 다음과 같습니다.
* Atoms
* ProgressButtonAtom
* Molecules
* SideButtons (합성컴포넌트)
* Clock
* Organisms
* CurrentTodoCard
* Components
* MainTodo
UI작업이 대부분이라 별 문제 없다면 머지하셔도 될 것 같습니다~
+) MainTodo 의 SideButtons들은 어떤 형태로 적용될지 모르니 핸들러를 만들지 않고 inline arrow function으로 두었는데, 
미리 정의해두면 좋을 것 같다 하시면 말씀해주세용~
#35 
#37 
#38
=> 35 todo 페이지 레이아웃 작성

src/DB/indexed.ts, src/DB/indexedAction.ts, src/components/TodoList.tsx
[이슈 링크](https://github.com/extreme-todo/frontend/issues/50)
=> Fix - #50 waitForInit 메소드 추가

src/organisms/CurrentTodoCard.tsx
- 조건이 잘못 설정되어서 발생하는 이슈였음. 조건 및 휴식 시점 수정하여 이슈 조치했습니다.
=> Fix : #60 계속 집중하기 기능 이슈 수정

fixture/mockTodoList.ts, src/DB/indexed.ts, src/components/AddTodo.tsx, src/components/TodoList.tsx, src/shared/apis.ts
따로 전달드릴 내용은 없습니다. 각 커밋의 커밋 코멘트를 참고해주시면 됩니다.
의견 있으시면 편하게 코멘트 남겨주세요 :)
=> Feature/66 할 일 추가 api

src/components/MainTodo.tsx, src/components/Setting.tsx, src/components/TodoList.tsx, src/hooks/useCurrentTodo.ts, src/hooks/useExtremeMode.tsx, src/molecules/CurrentTodo.tsx, src/molecules/ExtremeModeIndicator.tsx, src/organisms/CurrentTodoCard.tsx
=> 61 48 관련 연동 작업

src/DB/indexed.ts, src/DB/indexedCalc.ts, src/components/AddTodo.tsx, src/components/TodoList.tsx, src/molecules/CalendarInput.tsx, src/shared/apis.ts, src/test/DB/indexedCalc.spec.ts
- 지난 번 미팅 때 백엔드를 UTC 시간으로 수정한 것 때문에 코드를 테스트할 때 문제가 생겼습니다. 그래서 이 브랜치를 테스트 할 때는 백엔드 코드를 UTC시간으로 수정한 이전 커밋으로 checkout을 한 뒤에 테스트를 했습니다. 그때는 잘 됐습니다 :)
- 지난 번 미팅 때 이야기를 나눈대로 차후 작업에서 UTC 시간으로도 돌아갈 수 있도록 코드를 수정하도록 하겠습니다.
=> Feature/69 reorder api 작업

src/hooks/useCurrentTodo.ts, src/hooks/usePomodoro.tsx, src/shared/apis.ts
이전 PR은 develop 브랜치 반영을 안해서 내리고 다시 올립니다.
간단한 작업이니 리뷰 없이 머지해주셔도 됩니다~
참고 화면 캡쳐:
=> Create : #68 Timer API 추가

src/components/RankingAndRecords.tsx, src/hooks/useCurrentTodo.ts, src/hooks/usePomodoro.tsx, src/shared/apis.ts
timer api 와 동일하게 간단한 작업입니다~
결과 화면 참고:
=> Feature/77 ranking api 작업

src/components/Setting.tsx, src/shared/apis.ts, src/shared/interfaces.ts
=> 79 setting api 작업

src/components/MainTodo.tsx, src/components/Modal.tsx, src/components/TodoList.tsx, src/molecules/NowCard.tsx, src/molecules/TodoCard/content/TodoUI.tsx, src/molecules/TodoCard/index.tsx, src/shared/apis.ts, src/styles/Global.tsx, src/test/molecules/TodoCard.test.tsx
- 수정버튼과 같은 디자인으로 옆에 '삭제'버튼을 추가했습니다.
- 일전에 말씀드렸던 dnd를 적용하려고 했더니 UI적으로 만족스러운 결과물을 내기가 생각보다 쉽지 않았습니다. 그래서 빠르게 차선책을 구현해 보았습니다.
- 커밋 메시지에 이슈 넘버링이 달려있지 않은 커밋들은 이 이슈와는 상관없는 커밋들입니다! 생각나는 거 끄적이다 커밋하고 그랬었습니다 ㅎㅎ;;
- 더 좋은 아이디어, 수정 사항 있으시면 코멘트 남겨주세요 :)
=> Feature/87 delete UI 생성하기

src/App.tsx, src/components/TodoList.tsx, src/hooks/useCurrentTodo.ts, src/shared/apis.ts
- 이슈를 넘버링 하지 않은 커밋은 react query option과 관련한 커밋입니다.
=> 92 재발급된 id token 처리하기

fixture/mockTodoList.ts, src/DB/indexed.ts, src/DB/indexedAction.ts, src/components/AddTodo.tsx, src/components/TodoList.tsx, src/hooks/useCurrentTodo.ts, src/hooks/useEdit.tsx, src/molecules/TodoCard/index.tsx, src/shared/apis.ts, src/shared/todoModule.ts
- 위 사진처럼 id값이 생성됩니다.
- 좀 더 상세한 설명은 커밋 커멘트에 남겨두었습니다.
=> Feature/97 indexeddb의 id column 수정하기

src/components/Modal.tsx, src/components/Setting.tsx, src/hooks/useExtremeMode.tsx, src/shared/apis.ts, src/test/components/Setting.test.tsx, src/test/organisms/Records.test.tsx
=> 95 테스트 코드 깨지는 버그 수정

src/test/DB/indexedCalc.spec.ts
=> Update : #97 테스트 코드 수정

src/components/AddTodo.tsx, src/components/Modal.tsx, src/molecules/CategoryInput.tsx, src/shared/inputValidation.ts
- modal 컴포넌트 수정으로 인한 사이드 이펙트 수정을 담은 PR입니다.
- addTodo에서 Submit하고 나서도 모달이 닫히지 않게 하였지만, 이 때문에 새로운 todo가 등록되고 나서 다음 todo를 등록하기 편하게 title과 category input을 초기화 되지 않았습니다. 이 부분을 수정하였습니다.
- 기타 addTodo와 관련된 코드를 몇 가지 수정하였습니다. 직접적으로 관련된 이슈는 아니라 이슈 넘버링은 커밋 메시지에서 제외하였습니다.
=> Feature/102 modal 컴포넌트 수정

src/components/Welcome.tsx, src/styles/Global.tsx
- 버튼과 EXTREME TODO 타이틀 간 간격 조정
- 불필요한 프래그먼트 태그 제거
- 반응형 기본 font-size 설정
=> Update : #110 줄 간 간격 제거 및 반응형 최적화

src/components/RankingAndRecords.tsx, src/components/Welcome.tsx, src/hooks/useIsMobile.ts, src/molecules/CartegorySelector.tsx, src/molecules/CurrentTodo.tsx, src/molecules/RankingTexts.tsx, src/molecules/RecordCell.tsx, src/molecules/SideButtons.tsx, src/organisms/Ranking.tsx, src/organisms/Records.tsx, src/shared/constants.ts, src/styles/theme.ts
태블릿 세로, 모바일 세로 모드일 때 true를 리턴하는 훅을 만들었습니다.
반응형 작업할 때 편하지 않을까 합니다..
=> Responsive/115 ranking records 반응형 작업

src/components/Modal.tsx, src/components/PomodoroTimeSetting.tsx, src/components/TodoCard/content/EditUI.tsx, src/components/TodoCard/content/TodoUI.tsx, src/molecules/CategoryInput.tsx, src/organisms/CalendarInput.tsx, src/organisms/DateCard.tsx
- 뽀모도로 시간 셋팅 반응형 작업입니다.
- PC UI도 시간 설정 버튼이 작다고 느껴져서 키웠습니다 :)
- 그 외 제가 작업했던 부분들에서 font-size를 너무 임의대로 설정한 거 같아서 theme.ts에 정의된 font-size를 최대한 적용해 보았습니다. 해당 커밋은 이 브랜치와는 연관이 없어서 커밋 타이틀에 브랜치 넘버링을 하지 않았습니다.
=> 128 pomodoro modal 반응형

src/components/Modal.tsx
- 브랜치는 따로 파지 않았습니다~
- 미팅 때 공유해주신 addTodo 시 invalidateQueries 안되는 부분 수정했습니다.
=> BugFix : addTodo의 queryInvalidate 안 되는 부분 수정

src/components/Setting.tsx, src/hooks/useCurrentTodo.ts, src/hooks/useExtremeMode.tsx, src/hooks/usePomodoro.tsx, src/organisms/Records.tsx, src/shared/apis.ts, src/test/components/Setting.test.tsx
Timer 관련 메소드를 progress 제외 전부 제거했습니다.
그 외 특별한 사항은 없습니다!
=> Hotifx/161 be timer api 리팩토링 반영 작업

src/hooks/useCurrentTodo.ts, src/hooks/useExtremeMode.tsx, src/hooks/usePomodoro.tsx, src/molecules/RecordCell.tsx, src/organisms/CurrentTodoCard.tsx, src/organisms/Records.tsx
- Records UI 깨짐 현상 및 변경된 시간 단위 포매팅 수정 (분 단위 -> ms 단위)
- Extreme 모드 서버 반영 (Setting, 번개 아이콘 모두)
- currentTodo 진행상황 저장
- currentTodo 없는 경우 타이머 진행되지 않도록 수정
=> Hotfix/159 배포 후 찾은 hot fix 해야 될 내용들

src/components/Setting.tsx, src/hooks/useExtremeMode.tsx, src/molecules/ExtremeModeIndicator.tsx, src/test/components/Setting.test.tsx, src/test/hooks/useExtremeMode.test.tsx
제가 봐도 이상해서 수정했습니다.. 짚어주셔서 감사합니다!
=> Fix : #171 useExtremeMode 수정

src/hooks/LoginContext.tsx, src/shared/apis.ts, src/test/components/Modal.test.tsx, src/test/components/RankingAndRecords.test.tsx, src/test/components/Setting.test.tsx, src/test/hooks/LoginContext.test.tsx, src/test/hooks/useExtremeMode.test.tsx, src/test/organisms/Records.test.tsx
- 자주 사용되는 string value를 상수로 지정했습니다.
- 엑세스 토큰이 무효할 때 나오는 401에러에 대한 핸들링 코드를 추가했습니다.
=> 175 axios 단에서 에러 핸들링 코드 추가

src/atoms/CardAtom.tsx, src/components/MainTodo.tsx, src/components/Modal.tsx, src/molecules/Clock.tsx, src/molecules/CurrentTodo.tsx, src/molecules/SideButtons.tsx, src/organisms/CurrentTodoCard.tsx, src/styles/Global.tsx
- 디코에 말씀해주신 것과 제가 직전 pr에 코멘트 남긴대로 새롭게 설정한 theme 중심으로 수정해 보았습니다.
- 마음껏 코멘트로 의견 남겨주시면 됩니다! (원래 희정님 코드인 것들이 대부분이니 다 원위치 해도 상관없습니다 ㅋㅋㅋ)
- 한 가지 궁금한 게 있어서요! SideButton은 현재 BtnAtom을 랩핑한 것 같은데, 어떤 역할인지 궁금합니다. 컴파운드 패턴으로 사용하고 계시긴 하지만 컴파운드의 목표인 Prop Drilling을 해결하기 위해서나 내부가 어떤 UI인지 파악이 힘들 때를 해소하거나 하는 건 아닌 것 같고, 확장의 가능성 때문에 간단한 수정만 해서 사용하시는 건지 궁금합니다 :) ButtonWrapper도 있긴 해서 디자인 측면에서 묶어 두신 걸까 하고 추측해보기도 했는데 희정님의 의견도 듣고 싶습니다ㅋㅋ
=> Feature/179 todo 진행 화면 디자인 수정

src/atoms/InputAtom.tsx, src/styles/emotion.d.ts
- CSS에 theme을 경림님 작업에 맞게 다시 설정했습니다.
- Usual에서만 사용되는 속성이 있고 Underline에만 사용되는 속성이 있어서 나누어 보았습니다. '나누다 보니 확장성이 더 별로일까?' 싶기도 하고요. 추후에 또 달라질 수 있습니다!
- 일단은 휴가시니까 merge하고 이후 작업하도록 하겠습니다. 아마 다시 살펴보실 시간을 내기는 힘드실 거 같으니 오시면 개발자 미팅 때 브리핑 하도록 하겠습니다.
=> Refactor/184 inputatom 리팩토링

public/icon/delete.svg, public/icon/edit_handle.svg, src/atoms/InputAtom.tsx, src/atoms/PopperAtom.tsx, src/atoms/TomatoInput.tsx, src/components/AddTodo.tsx, src/components/Setting.tsx, src/components/TodoCard/content/TodoUI.tsx, src/components/TodoCard/index.tsx, src/hooks/useEdit.tsx, src/molecules/CategoryInput.tsx, src/molecules/DayPickerUI.tsx, src/molecules/ExtremeModeIndicator.tsx, src/test/components/TodoCard.test.tsx, src/test/molecules/CategoryInput.test.tsx
- 작업 내용은 커밋 코멘트를 참고해주세요 :)
- 다양한 의견 코멘트로 남겨주시면 감사하겠습니다 🙇‍♂️
=> Refactor/198 editui 리팩토링

src/atoms/CardAnimationPlayer.tsx, src/atoms/Overlay.tsx, src/hooks/usePomodoro.tsx, src/molecules/Clock.tsx, src/molecules/CurrentTodo.tsx, src/organisms/CurrentTodoCard.tsx, src/organisms/RestCard.tsx, src/styles/cardAnimations.ts, src/test/molecules/CategoryList.test.tsx, src/test/molecules/Clock.test.tsx, src/test/molecules/CurrentTodo.test.tsx, src/test/organisms/RestCard.test.tsx
다시 한 번 테스트 코드를 늦게 작성한 점 양해 부탁드립니다ㅜㅜ 다음 작업부터는 제대로 테스트 코드 먼저 작성하도록 하겠습니다!
오랜만에 테스트 코드를 작성해서 좀 이상한 부분 있으면 바로 말씀 부탁드립니다~
=> Refactor/194 테스트 코드 작성

src/components/PomodoroTimeSetting.tsx, src/test/components/PomodoroTimeSetting.test.tsx
- mock handler 이름 실제 코드와 통일했습니다.
- props 수정된 것 반영했습니다.
- 누락된 arialabel 추가했습니다.
=> Refactor : #203 테스트 코드 수정

package-lock.json, package.json, src/DB/indexed.ts, src/DB/indexedAction.ts, src/__mocks__/tabbable.js, src/atoms/BtnAtom.tsx, src/atoms/InputAtom.tsx, src/atoms/TomatoInput.tsx, src/components/AddTodo.tsx, src/components/PomodoroTimeSetting.tsx, src/components/TodoCard/index.tsx, src/components/TodoList/index.tsx, src/molecules/CategoryInput.tsx, src/molecules/CurrentTodo.tsx, src/molecules/ExtremeModeIndicator.tsx, src/molecules/SideButtons.tsx, src/organisms/NoTodoCard.tsx, src/organisms/RestCard.tsx, src/shared/inputValidation.ts, src/styles/Global.tsx, src/test/components/AddTodo.test.tsx
@imhjnoh 중간 PR입니다!
EditTodo에 대한 작업이 남았지만 AddTodo까지만 작업을 완료해서 올립니다.
가장 마지막 미팅 때 보셨던 것에서 경림님과 이야기 나누었던 Title validation feedback수정, category validation CSS 추가했습니다.
더불어 AddTodo 안에서 tab으로 input들을 돌아다니게 하면 PC에서 유저 편의성이 좋을 거 같아서 그 부분에 대한 작업을 더했습니다.
EditTodo도 이어서 작업해보겠습니다
=> Validation logic 개선하기

.husky/pre-push, src/__test__/hooks/useExtremeMode.test.tsx, src/__test__/hooks/usePomodoro.test.tsx, src/hooks/useExtremeMode.tsx, src/molecules/ExtremeModeIndicator.tsx
=> Bugfix/226 버그 수정
